services:
  monitor: 
    ports: 
      - "9229:9229"
      - "8080:8080"
  redis-commander:
    image: ghcr.io/joeferner/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
  redis: 
    ports:
      - "6379:6379"
  postgres:
    ports:
      - "5432:5432"
